### ISSUE TITLE
xl2tpd makes kernel soft lockup

### ISSUE THREAD

**Issue by starrose** [xelerance/xl2tpd#109]
xl2tpd 1.3.6 makes the kernel soft lockup and freeze all the system.
I use the command 
 "echo 'c xxx' > /var/run/xl2tpd/l2tp-control"  xxx is the name of tunnel.
I have submit the bug to Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822801.

I compile the 1.3.7 by my self. And the problem seems still exist.

**Comment by patrakov** [comment]
The deadlock is likely fixed in the kernel, by commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=55454a565836e1cb002d433e901804dea4406a32

However, after that, when trying to use L2TP over a 3G connection, I get "ppp0: recursion detected", and the tunnel still doesn't work.

Possibly related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856655

**Comment by Lourens-Rich** [comment]
This problem still exist for me.
`Aug 24 06:52:36 moon NetworkManager[1344]: <info>  [1503546756.7587] manager: NetworkManager state is now CONNECTED_LOCAL
Aug 24 06:52:36 moon NetworkManager[1344]: <info>  [1503546756.7589] manager: NetworkManager state is now CONNECTED_SITE
Aug 24 06:52:36 moon NetworkManager[1344]: <info>  [1503546756.7591] dns-mgr: Writing DNS information to /usr/bin/resolvconf
Aug 24 06:52:37 moon nm-dispatcher[1348]: req:3 'vpn-up' [ppp0]: new request (0 scripts)
Aug 24 06:52:37 moon nm-dispatcher[1348]: req:3 'vpn-up' [ppp0]: completed: no scripts
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:46 moon kernel: ppp0: recursion detected
Aug 24 06:52:47 moon systemd-timesyncd[380]: Timed out waiting for reply from 78.36.11.161:123 (3.arch.pool.ntp.org).
Aug 24 06:52:56 moon kernel: net_ratelimit: 12 callbacks suppressed
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:56 moon kernel: ppp0: recursion detected
Aug 24 06:52:57 moon systemd-timesyncd[380]: Timed out waiting for reply from 91.206.16.3:123 (3.arch.pool.ntp.org).
Aug 24 06:52:57 moon systemd-timesyncd[380]: Synchronized to time server 85.21.78.91:123 (3.arch.pool.ntp.org).
Aug 24 06:53:01 moon NetworkManager[1344]: <info>  [1503546781.5675] connectivity: (enp2s0) timed out
Aug 24 06:53:01 moon NetworkManager[1344]: <info>  [1503546781.5677] manager: NetworkManager state is now CONNECTED_GLOBAL`

**Comment by shussain** [comment]
1.3.10 has a fix for xl2tpd-control (commit cdc973d8f953bc43726139289aa8fd0ee7a6698e).

Closing this ticket but if this issue still occurs with 1.3.10 (or later releases), please reopen this ticket or open a new ticket.
